# 0. Numerical Python (NumPy)

Numpy library: 고성능 수치계산을 위해 만들어진 파이썬 라이브러리

In [2]:
import numpy as np

# 1. Array 생성하기
#### 1. np.arange(n)
- 0부터 n-1까지의 정수로 이루어진 1차원의 array 생성

In [3]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

#### 2. np.arange(start, stop, stepsize)

In [5]:
n = np.arange(0, 30, 2) 
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### 3. np.array()
- 다차원의 array를 생성할 수 있음
- 함수의 입력값은 반드시 array(e.g., python list)여야함

In [3]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [4]:
m.shape

(2, 3)

#### 4. np.linspace(start, stop, array에 들어갈 숫자의 개수)

In [6]:
o = np.linspace(0, 4, 9) 
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

#### 5. 그 외

In [7]:
x = np.ones((3, 2)) #모든 값이 1인 3행 2열의 array
print(x)

y = np.zeros((2, 3))#모든 값이 0인 2행 3열의 array
print(y)

z = np.eye(3) #대각선의 값이 3개인 array
print(z)

u = np.array([1,2,3]) 
np.diag(u) # 1,2,3을 대각선 위치에 지니는 array

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### 5. np.repeat

In [8]:
np.array([1, 2, 3] * 3) #리스트 자체를 3번 반복

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [9]:
np.repeat([1, 2, 3], 3) #행렬의 각 숫자를 3번씩 반복

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

# 2. Manipulating array shapes
#### 1. reshape and resize
- 공통점: array의 크기를 변환
- 차이점: reshape는 원본을 변경하지 않음, resize는 원본을 변경

In [10]:
a = np.arange(0, 30, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [11]:
n = a.reshape(3, 5) #3행 5열의 array로 변경
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [41]:
print(a) #reshape는 원본을 변경하지 않음

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [13]:
o = np.linspace(0, 4, 9) 
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [14]:
o.resize(3, 3) #3행 3열의 array로 변경
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [15]:
print(o) #resize는 원본을 변경

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


#### 2. ravel and flatten 
- 공통점: 1차원의 array로 바꿔줌
- 차이점: ravel은 원본의 view를 반환, flatten은 복사본을 반환

In [4]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# 3. Combining arrays
- `vstack` : stack arrays in sequence vertically (row wise)
- `hstack`: stack arrays in sequence horizontally (column wise)

In [44]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [45]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [46]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# 4. Spliting arrays
- hsplit : 수평축으로 분할
![title](hsplit.png)
<br>
- vsplit : 수직축으로 분할
![title](vsplit.png)
<br>
(출처:https://rfriend.tistory.com/359)



In [14]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.hsplit(a, 3) #a라는 array을 수평축을 기준으로 세부분으로 분할

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [18]:
np.vsplit(a,3) #a라는 array을 수직축을 기준으로 세부분으로 분할

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

# 5. Operation

In [47]:
x = np.array([1,2,3])
y = np.array([4,5,6])

- +(덧셈), -(뺄셈), * (곱셈), /(나눗셈), ** (제곱) 

In [48]:
print(x + y) # array의 값들 간의 덧셈 [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # array의 값들 간의 뺄셈  [1 2 3] - [4 5 6] = [-3 -3 -3]

print(x * y) # array의 값들 간의 곱셈  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # array의 값들 간의 나눗셈  [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

print(x**2) # array의 값들에 대해 제곱  [1 2 3] ^2 =  [1 4 9]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


- Dot Product: 두 가지 행렬을 곱하는 것과 같은 방식

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3 $


In [49]:
print(x.dot(y))
print(np.dot(x,y))

32
32


# 6. Transposing array
- array의 행,열을 서로 바꿈

In [50]:
import numpy as np

z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [51]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

# 7. dtype, astype
- dtype: 데이터 타입 확인
- astype: 데이터 타입 바꾸기

In [52]:
z.dtype

dtype('int32')

In [53]:
z = z.astype('f') 
z.dtype

dtype('float32')

# 8. Math Functions

#### 1. sum, max, min, mean, std 함수

In [54]:
a = np.array([-4, -2, 1, 3, 5])

print(a.sum())
print(a.max())
print(a.mean())
print(a.std())

3
5
0.6
3.2619012860600183


#### 2.`argmax` 와 `argmin` 함수는 최대값, 최솟값의 index를 반환

In [55]:
a.argmax()

4

# 9. Indexing and Slicing

In [17]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [18]:
r[2, 2] 

14

In [19]:
r[3, 3:6] 

array([21, 22, 23])

In [20]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [21]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# 10. Copying Data
- array를 수정하면 원본 역시 바뀜

In [22]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [23]:
r2 = r[:3,:3]
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
r #원래 array도 변화

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

- 원래 array도 변하는 것을 막기 위해선, `.copy`로 copy를 만들어야함 

In [25]:
r_copy = r.copy()
r_copy[:] = 10
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [26]:
r #원래 array는 변화하지 않음

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# 11. Array의 요소 반복하기

In [27]:
test = np.random.randint(0, 10, (4,3)) #create a new 4 by 3 array of random numbers 0-9
test

array([[9, 4, 2],
       [3, 4, 4],
       [9, 8, 6],
       [5, 1, 9]])

#### 1. 행을 반복하기

In [66]:
for row in test: 
    print(row)

[4 5 4]
[6 2 4]
[3 1 8]
[3 8 1]


#### 2. index와 행 반복하기

In [67]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [4 5 4]
row 1 is [6 2 4]
row 2 is [3 1 8]
row 3 is [3 8 1]


#### 3. `zip` 을 이용하여 2가지 이상의 array 반복

In [29]:
test2 = test**2
test2

array([[81, 16,  4],
       [ 9, 16, 16],
       [81, 64, 36],
       [25,  1, 81]], dtype=int32)

In [30]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[9 4 2] + [81 16  4] = [90 20  6]
[3 4 4] + [ 9 16 16] = [12 20 20]
[9 8 6] + [81 64 36] = [90 72 42]
[5 1 9] + [25  1 81] = [30  2 90]


# 12. Converting arrays
- NumPy array를 Python list로 변경: `tolist` 함수 사용

In [20]:
r = np.arange(9)
r.resize((3, 3))
r

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
r.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]